# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'API' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for API

end

target 'ClearScore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ClearScore

end

target 'ClearScoreUIKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ClearScoreUIKit

end

target 'Domain' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Domain

end
